---
# Set hostnames
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ instances[item].hostname }}"
  when: ansible_host == "{{ instances[item].ip }}"
  loop: "{{ instances.keys() }}"

- name: Replace a localhost entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: 127.0.1.1       {{ instances[item].hostname }}
    owner: root
    group: root
    mode: '0644'
  when: ansible_host == "{{ instances[item].ip }}"
  loop: "{{ instances.keys() }}"

# install nginx
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

# Install python3 
- name: Install python3
  apt:
    name: python3
    state: present
    update_cache: yes

# Install pip
- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

# Install flask
- name: Install flask
  ansible.builtin.shell: "pip install flask"

# Install fabric
- name: Install fabric
  ansible.builtin.shell: "pip install fabric"

# Install metasploit
- name: Install metasploit
  apt:
    name: metasploit-framework
    state: present
    update_cache: yes

# Install powershell-empire
- name: Install powershell-empire
  apt:
    name: powershell-empire
    state: present
    update_cache: yes

# Install RustDesk 
- name: Install wget
  apt:
    name: wget
    state: present
    update_cache: yes

- name: wget rustdesk
  ansible.builtin.shell: wget https://github.com/rustdesk/rustdesk/releases/download/1.2.3-1/rustdesk-1.2.3-0-x86_64.pkg.tar.zst

- name: extract
  ansible.builtin.shell: tar -xvf rustdesk* -C /

- name: move files
  ansible.builtin.shell: cp /usr/share/rustdesk/files/rustdesk.service /etc/systemd/system/

- name: start
  ansible.builtin.shell: systemctl start rustdesk.service

- name: enable
  ansible.builtin.shell: systemctl enable rustdesk.service

- name: remove package
  ansible.builtin.shell: rm rustdesk*

- name: set password
  ansible.builtin.shell: rustdesk --password redpass123